-- n8n 데이터베이스 초기 설정
-- MySQL Exporter용 권한 설정

CREATE USER IF NOT EXISTS 'exporter'@'%' IDENTIFIED BY '7345' WITH MAX_USER_CONNECTIONS 3;
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%';
FLUSH PRIVILEGES;
